import type { Metadata } from "next";
import "@ceskysoftware/components/styles";
import { Aside } from "@/features/aside";
import { LayoutX } from "@/components/LayoutX";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutX>{children}</LayoutX>
      </body>
    </html>
  );
}
