import type { Metadata } from "next";
import "@ceskysoftware/components/styles";
import { LayoutX } from "@/components/LayoutX";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modals,
}: {
  children: React.ReactNode;
  modals: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutX>{children}</LayoutX>
        {modals}
      </body>
    </html>
  );
}
